DEF VAR i AS INT.

DO i = 1 TO NUM-DBS WITH FRAME x DOWN:
/*DISPLAY LDBNAME(i) .  */
CREATE ALIAS DICTDB FOR DATABASE VALUE(LDBNAME(i)).
RUN /home/qadeeitg/tools/checkDB.p "fullOnly".
END.
CREATE ALIAS DICTDB FOR DATABASE VALUE(LDBNAME(1)).
