DEF VAR i AS INT.

DO i = 1 TO NUM-DBS WITH FRAME x DOWN:
   CREATE ALIAS DICTDB FOR DATABASE VALUE(LDBNAME(i)).
   RUN /opt/qadee/local/bin/admin/maint/src/xxbldstrct.p.
END.
CREATE ALIAS DICTDB FOR DATABASE VALUE(LDBNAME(1)).
